# block_type, in_channels, out_channels, stride, kernel_size, group, activation, se, kwargs
model_config: [["Conv", 3, 64, 2, 3, 1, "prelu", {}],
               ["Conv", 64, 64, 1, 3, 64, "prelu", {}],
               ["Mobile", 64, 64, 2, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 64, 64, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 64, 64, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 64, 64, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 64, 64, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 64, 128, 2, 3, 1, "prelu", {"expansion_rate": 4}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 2, 3, 1, "prelu", {"expansion_rate": 4}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Mobile", 128, 128, 1, 3, 1, "prelu", {"expansion_rate": 2}],
               ["Conv", 128, 512, 1, 1, 1, "prelu", {}],
               ["Conv", 512, 512, 1, 7, 512, None, {}],
               ["Conv", 512, 256, 1, 1, 1, None, {}],
               ["global_average", 0, 0, 0, 0, 0, 0, {}]]
